<a href="https://colab.research.google.com/github/Sinudeshmukh/Data-Science/blob/main/AssociationRulesAssgn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [3]:
book = pd.read_csv('book.csv')
book

      ChildBks  YouthBks  CookBks  ...  ItalAtlas  ItalArt  Florence
0            0         1        0  ...          0        0         0
1            1         0        0  ...          0        0         0
2            0         0        0  ...          0        0         0
3            1         1        1  ...          0        0         0
4            0         0        1  ...          0        0         0
...        ...       ...      ...  ...        ...      ...       ...
1995         0         0        1  ...          0        1         1
1996         0         0        0  ...          0        0         0
1997         0         0        0  ...          0        0         0
1998         0         0        1  ...          0        0         0
1999         0         0        0  ...          0        0         0

[2000 rows x 11 columns]

##Apriori Algorithm

####With Min_Support 0.18

In [12]:
freq_itemsets = apriori(book,min_support=0.18,use_colnames=True)
freq_itemsets

    support              itemsets
0    0.4230            (ChildBks)
1    0.2475            (YouthBks)
2    0.4310             (CookBks)
3    0.2820            (DoItYBks)
4    0.2145              (RefBks)
5    0.2410              (ArtBks)
6    0.2760             (GeogBks)
7    0.2560   (ChildBks, CookBks)
8    0.1840  (ChildBks, DoItYBks)
9    0.1950   (ChildBks, GeogBks)
10   0.1875   (CookBks, DoItYBks)
11   0.1925    (CookBks, GeogBks)

####With Min_Support=0.15

In [14]:
freq_itemsets1 = apriori(book,min_support=0.15,use_colnames=True)
freq_itemsets1

    support              itemsets
0    0.4230            (ChildBks)
1    0.2475            (YouthBks)
2    0.4310             (CookBks)
3    0.2820            (DoItYBks)
4    0.2145              (RefBks)
5    0.2410              (ArtBks)
6    0.2760             (GeogBks)
7    0.1650  (ChildBks, YouthBks)
8    0.2560   (ChildBks, CookBks)
9    0.1840  (ChildBks, DoItYBks)
10   0.1515    (ChildBks, RefBks)
11   0.1625    (ArtBks, ChildBks)
12   0.1950   (ChildBks, GeogBks)
13   0.1620   (YouthBks, CookBks)
14   0.1875   (CookBks, DoItYBks)
15   0.1525     (CookBks, RefBks)
16   0.1670     (ArtBks, CookBks)
17   0.1925    (CookBks, GeogBks)

####With Min_Support 0.1

In [15]:
freq_itemsets2 = apriori(book, min_support=0.1,use_colnames=True)
freq_itemsets2

    support                       itemsets
0    0.4230                     (ChildBks)
1    0.2475                     (YouthBks)
2    0.4310                      (CookBks)
3    0.2820                     (DoItYBks)
4    0.2145                       (RefBks)
5    0.2410                       (ArtBks)
6    0.2760                      (GeogBks)
7    0.1135                     (ItalCook)
8    0.1085                     (Florence)
9    0.1650           (ChildBks, YouthBks)
10   0.2560            (ChildBks, CookBks)
11   0.1840           (ChildBks, DoItYBks)
12   0.1515             (ChildBks, RefBks)
13   0.1625             (ArtBks, ChildBks)
14   0.1950            (ChildBks, GeogBks)
15   0.1620            (YouthBks, CookBks)
16   0.1155           (YouthBks, DoItYBks)
17   0.1010             (ArtBks, YouthBks)
18   0.1205            (YouthBks, GeogBks)
19   0.1875            (CookBks, DoItYBks)
20   0.1525              (CookBks, RefBks)
21   0.1670              (ArtBks, CookBks)
22   0.1925             (CookBks, GeogBks)
23   0.1135            (ItalCook, CookBks)
24   0.1055             (RefBks, DoItYBks)
25   0.1235             (ArtBks, DoItYBks)
26   0.1325            (DoItYBks, GeogBks)
27   0.1105              (RefBks, GeogBks)
28   0.1275              (ArtBks, GeogBks)
29   0.1290  (ChildBks, YouthBks, CookBks)
30   0.1460  (ChildBks, CookBks, DoItYBks)
31   0.1225    (ChildBks, CookBks, RefBks)
32   0.1265    (ArtBks, ChildBks, CookBks)
33   0.1495   (ChildBks, CookBks, GeogBks)
34   0.1045  (ChildBks, DoItYBks, GeogBks)
35   0.1020    (ArtBks, ChildBks, GeogBks)
36   0.1015    (ArtBks, CookBks, DoItYBks)
37   0.1085   (CookBks, DoItYBks, GeogBks)
38   0.1035     (ArtBks, CookBks, GeogBks)

#Association Rules

###Using 0.18 Min_Support and Metric='Lift'

In [16]:
rules = association_rules(freq_itemsets,metric='lift',min_threshold=0.7)
rules

  antecedents consequents  antecedent support  ...      lift  leverage  conviction
0  (ChildBks)   (CookBks)               0.423  ...  1.404179  0.073687    1.441240
1   (CookBks)  (ChildBks)               0.431  ...  1.404179  0.073687    1.421069
2  (ChildBks)  (DoItYBks)               0.423  ...  1.542511  0.064714    1.270770
3  (DoItYBks)  (ChildBks)               0.282  ...  1.542511  0.064714    1.660347
4  (ChildBks)   (GeogBks)               0.423  ...  1.670264  0.078252    1.343211
5   (GeogBks)  (ChildBks)               0.276  ...  1.670264  0.078252    1.966074
6   (CookBks)  (DoItYBks)               0.431  ...  1.542677  0.065958    1.270875
7  (DoItYBks)   (CookBks)               0.282  ...  1.542677  0.065958    1.697968
8   (CookBks)   (GeogBks)               0.431  ...  1.618245  0.073544    1.308361
9   (GeogBks)   (CookBks)               0.276  ...  1.618245  0.073544    1.880766

[10 rows x 9 columns]

###Using 0.18 Min_Support and Metric='Confidence'

In [24]:
rules1 = association_rules(freq_itemsets,metric='confidence',min_threshold=0.6)
rules1

  antecedents consequents  antecedent support  ...      lift  leverage  conviction
0  (ChildBks)   (CookBks)               0.423  ...  1.404179  0.073687    1.441240
1  (DoItYBks)  (ChildBks)               0.282  ...  1.542511  0.064714    1.660347
2   (GeogBks)  (ChildBks)               0.276  ...  1.670264  0.078252    1.966074
3  (DoItYBks)   (CookBks)               0.282  ...  1.542677  0.065958    1.697968
4   (GeogBks)   (CookBks)               0.276  ...  1.618245  0.073544    1.880766

[5 rows x 9 columns]

###Using 0.15 Min_Support and Metric='Lift'

In [22]:
rules_1 = association_rules(freq_itemsets1,metric='lift',min_threshold=0.7)
rules_1

   antecedents consequents  antecedent support  ...      lift  leverage  conviction
0   (ChildBks)  (YouthBks)              0.4230  ...  1.576044  0.060308    1.233750
1   (YouthBks)  (ChildBks)              0.2475  ...  1.576044  0.060308    1.731000
2   (ChildBks)   (CookBks)              0.4230  ...  1.404179  0.073687    1.441240
3    (CookBks)  (ChildBks)              0.4310  ...  1.404179  0.073687    1.421069
4   (ChildBks)  (DoItYBks)              0.4230  ...  1.542511  0.064714    1.270770
5   (DoItYBks)  (ChildBks)              0.2820  ...  1.542511  0.064714    1.660347
6   (ChildBks)    (RefBks)              0.4230  ...  1.669725  0.060767    1.223818
7     (RefBks)  (ChildBks)              0.2145  ...  1.669725  0.060767    1.964548
8     (ArtBks)  (ChildBks)              0.2410  ...  1.594028  0.060557    1.771427
9   (ChildBks)    (ArtBks)              0.4230  ...  1.594028  0.060557    1.232464
10  (ChildBks)   (GeogBks)              0.4230  ...  1.670264  0.078252    1.343211
11   (GeogBks)  (ChildBks)              0.2760  ...  1.670264  0.078252    1.966074
12  (YouthBks)   (CookBks)              0.2475  ...  1.518667  0.055328    1.647105
13   (CookBks)  (YouthBks)              0.4310  ...  1.518667  0.055328    1.205678
14   (CookBks)  (DoItYBks)              0.4310  ...  1.542677  0.065958    1.270875
15  (DoItYBks)   (CookBks)              0.2820  ...  1.542677  0.065958    1.697968
16   (CookBks)    (RefBks)              0.4310  ...  1.649549  0.060050    1.215621
17    (RefBks)   (CookBks)              0.2145  ...  1.649549  0.060050    1.968556
18    (ArtBks)   (CookBks)              0.2410  ...  1.607763  0.063129    1.853095
19   (CookBks)    (ArtBks)              0.4310  ...  1.607763  0.063129    1.239125
20   (CookBks)   (GeogBks)              0.4310  ...  1.618245  0.073544    1.308361
21   (GeogBks)   (CookBks)              0.2760  ...  1.618245  0.073544    1.880766

[22 rows x 9 columns]

In [23]:
rules_2 = association_rules(freq_itemsets1,metric='confidence',min_threshold=0.7)
rules_2

  antecedents consequents  antecedent support  ...      lift  leverage  conviction
0    (RefBks)  (ChildBks)              0.2145  ...  1.669725  0.060767    1.964548
1   (GeogBks)  (ChildBks)              0.2760  ...  1.670264  0.078252    1.966074
2    (RefBks)   (CookBks)              0.2145  ...  1.649549  0.060050    1.968556

[3 rows x 9 columns]

###Using 0.15 Min_Support and Metric='lift'

In [26]:
rules_3 = association_rules(freq_itemsets2,metric='lift',min_threshold=1)
rules_3

           antecedents         consequents  ...  leverage  conviction
0           (ChildBks)          (YouthBks)  ...  0.060308    1.233750
1           (YouthBks)          (ChildBks)  ...  0.060308    1.731000
2           (ChildBks)           (CookBks)  ...  0.073687    1.441240
3            (CookBks)          (ChildBks)  ...  0.073687    1.421069
4           (ChildBks)          (DoItYBks)  ...  0.064714    1.270770
..                 ...                 ...  ...       ...         ...
95   (ArtBks, GeogBks)           (CookBks)  ...  0.048547    3.022812
96  (CookBks, GeogBks)            (ArtBks)  ...  0.057107    1.641657
97            (ArtBks)  (CookBks, GeogBks)  ...  0.057107    1.415327
98           (CookBks)   (ArtBks, GeogBks)  ...  0.048547    1.148237
99           (GeogBks)   (ArtBks, CookBks)  ...  0.057408    1.332800

[100 rows x 9 columns]

###Using 0.15 Min_Support and Metric='Confidence'

In [27]:
rules_4 = association_rules(freq_itemsets2,metric='confidence',min_threshold=0.7)
rules_4

             antecedents consequents  ...  leverage  conviction
0               (RefBks)  (ChildBks)  ...  0.060767    1.964548
1              (GeogBks)  (ChildBks)  ...  0.078252    1.966074
2               (RefBks)   (CookBks)  ...  0.060050    1.968556
3             (ItalCook)   (CookBks)  ...  0.064582         inf
4   (ChildBks, YouthBks)   (CookBks)  ...  0.057885    2.607917
5    (YouthBks, CookBks)  (ChildBks)  ...  0.060474    2.832545
6   (ChildBks, DoItYBks)   (CookBks)  ...  0.066696    2.755158
7    (CookBks, DoItYBks)  (ChildBks)  ...  0.066687    2.606928
8     (ChildBks, RefBks)   (CookBks)  ...  0.057204    2.972534
9      (CookBks, RefBks)  (ChildBks)  ...  0.057993    2.933083
10    (ArtBks, ChildBks)   (CookBks)  ...  0.056462    2.568403
11     (ArtBks, CookBks)  (ChildBks)  ...  0.055859    2.379235
12   (ChildBks, GeogBks)   (CookBks)  ...  0.065455    2.438571
13    (CookBks, GeogBks)  (ChildBks)  ...  0.068072    2.583081
14   (DoItYBks, GeogBks)  (ChildBks)  ...  0.048452    2.730446
15     (ArtBks, GeogBks)  (ChildBks)  ...  0.048067    2.885000
16    (ArtBks, DoItYBks)   (CookBks)  ...  0.048272    3.194159
17   (DoItYBks, GeogBks)   (CookBks)  ...  0.051392    3.141354
18     (ArtBks, GeogBks)   (CookBks)  ...  0.048547    3.022812

[19 rows x 9 columns]